stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven
      shellScript: mvn clean package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo
      registry: 127.0.0.1:34490
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
