stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven
      shellScript: package -Dmaven.test.skip=true
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demo
      registry: 127.0.0.1:34490
timeout: 60
notification: {}
